<?xml version="1.0" encoding="utf-8"?><Database Name="SomeDB" Class="SomeDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=SomeDB;Integrated Security=True;Connect Timeout=160" SettingsObjectName="RogerWaters.RealTimeDb.TestClient.Properties.Settings" SettingsPropertyName="SomeDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.empty" Member="empty">
    <Type Name="empty">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MyTable2" Member="MyTable2">
    <Type Name="MyTable2">
      <Column Name="MyTable2_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[some]" Member="some" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MyTable" Member="MyTable">
    <Type Name="MyTable">
      <Column Name="MyTable_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[some]" Member="some" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>