#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RogerWaters.RealTimeDb.TestClient
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="tpcc")]
	public partial class TPCCDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void Insertwarehouse(warehouse instance);
    partial void Updatewarehouse(warehouse instance);
    partial void Deletewarehouse(warehouse instance);
    partial void Insertdistrict(district instance);
    partial void Updatedistrict(district instance);
    partial void Deletedistrict(district instance);
    partial void Insertitem(item instance);
    partial void Updateitem(item instance);
    partial void Deleteitem(item instance);
    partial void Insertstock(stock instance);
    partial void Updatestock(stock instance);
    partial void Deletestock(stock instance);
    #endregion
		
		public TPCCDataContext() : 
				base(global::RogerWaters.RealTimeDb.TestClient.Properties.Settings.Default.tpccConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TPCCDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TPCCDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TPCCDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TPCCDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<customer> customer
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
		
		public System.Data.Linq.Table<warehouse> warehouse
		{
			get
			{
				return this.GetTable<warehouse>();
			}
		}
		
		public System.Data.Linq.Table<district> district
		{
			get
			{
				return this.GetTable<district>();
			}
		}
		
		public System.Data.Linq.Table<history> history
		{
			get
			{
				return this.GetTable<history>();
			}
		}
		
		public System.Data.Linq.Table<item> item
		{
			get
			{
				return this.GetTable<item>();
			}
		}
		
		public System.Data.Linq.Table<new_order> new_order
		{
			get
			{
				return this.GetTable<new_order>();
			}
		}
		
		public System.Data.Linq.Table<order_line> order_line
		{
			get
			{
				return this.GetTable<order_line>();
			}
		}
		
		public System.Data.Linq.Table<orders> orders
		{
			get
			{
				return this.GetTable<orders>();
			}
		}
		
		public System.Data.Linq.Table<stock> stock
		{
			get
			{
				return this.GetTable<stock>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customer")]
	public partial class customer
	{
		
		private int _c_id;
		
		private byte _c_d_id;
		
		private int _c_w_id;
		
		private System.Nullable<decimal> _c_discount;
		
		private System.Nullable<decimal> _c_credit_lim;
		
		private string _c_last;
		
		private string _c_first;
		
		private string _c_credit;
		
		private System.Nullable<decimal> _c_balance;
		
		private System.Nullable<decimal> _c_ytd_payment;
		
		private System.Nullable<short> _c_payment_cnt;
		
		private System.Nullable<short> _c_delivery_cnt;
		
		private string _c_street_1;
		
		private string _c_street_2;
		
		private string _c_city;
		
		private string _c_state;
		
		private string _c_zip;
		
		private string _c_phone;
		
		private System.Nullable<System.DateTime> _c_since;
		
		private string _c_middle;
		
		private string _c_data;
		
		public customer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_id", DbType="Int NOT NULL")]
		public int c_id
		{
			get
			{
				return this._c_id;
			}
			set
			{
				if ((this._c_id != value))
				{
					this._c_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_d_id", DbType="TinyInt NOT NULL")]
		public byte c_d_id
		{
			get
			{
				return this._c_d_id;
			}
			set
			{
				if ((this._c_d_id != value))
				{
					this._c_d_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_w_id", DbType="Int NOT NULL")]
		public int c_w_id
		{
			get
			{
				return this._c_w_id;
			}
			set
			{
				if ((this._c_w_id != value))
				{
					this._c_w_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_discount", DbType="SmallMoney")]
		public System.Nullable<decimal> c_discount
		{
			get
			{
				return this._c_discount;
			}
			set
			{
				if ((this._c_discount != value))
				{
					this._c_discount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_credit_lim", DbType="Money")]
		public System.Nullable<decimal> c_credit_lim
		{
			get
			{
				return this._c_credit_lim;
			}
			set
			{
				if ((this._c_credit_lim != value))
				{
					this._c_credit_lim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_last", DbType="Char(16)")]
		public string c_last
		{
			get
			{
				return this._c_last;
			}
			set
			{
				if ((this._c_last != value))
				{
					this._c_last = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_first", DbType="Char(16)")]
		public string c_first
		{
			get
			{
				return this._c_first;
			}
			set
			{
				if ((this._c_first != value))
				{
					this._c_first = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_credit", DbType="Char(2)")]
		public string c_credit
		{
			get
			{
				return this._c_credit;
			}
			set
			{
				if ((this._c_credit != value))
				{
					this._c_credit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_balance", DbType="Money")]
		public System.Nullable<decimal> c_balance
		{
			get
			{
				return this._c_balance;
			}
			set
			{
				if ((this._c_balance != value))
				{
					this._c_balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_ytd_payment", DbType="Money")]
		public System.Nullable<decimal> c_ytd_payment
		{
			get
			{
				return this._c_ytd_payment;
			}
			set
			{
				if ((this._c_ytd_payment != value))
				{
					this._c_ytd_payment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_payment_cnt", DbType="SmallInt")]
		public System.Nullable<short> c_payment_cnt
		{
			get
			{
				return this._c_payment_cnt;
			}
			set
			{
				if ((this._c_payment_cnt != value))
				{
					this._c_payment_cnt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_delivery_cnt", DbType="SmallInt")]
		public System.Nullable<short> c_delivery_cnt
		{
			get
			{
				return this._c_delivery_cnt;
			}
			set
			{
				if ((this._c_delivery_cnt != value))
				{
					this._c_delivery_cnt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_street_1", DbType="Char(20)")]
		public string c_street_1
		{
			get
			{
				return this._c_street_1;
			}
			set
			{
				if ((this._c_street_1 != value))
				{
					this._c_street_1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_street_2", DbType="Char(20)")]
		public string c_street_2
		{
			get
			{
				return this._c_street_2;
			}
			set
			{
				if ((this._c_street_2 != value))
				{
					this._c_street_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_city", DbType="Char(20)")]
		public string c_city
		{
			get
			{
				return this._c_city;
			}
			set
			{
				if ((this._c_city != value))
				{
					this._c_city = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_state", DbType="Char(2)")]
		public string c_state
		{
			get
			{
				return this._c_state;
			}
			set
			{
				if ((this._c_state != value))
				{
					this._c_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_zip", DbType="Char(9)")]
		public string c_zip
		{
			get
			{
				return this._c_zip;
			}
			set
			{
				if ((this._c_zip != value))
				{
					this._c_zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_phone", DbType="Char(16)")]
		public string c_phone
		{
			get
			{
				return this._c_phone;
			}
			set
			{
				if ((this._c_phone != value))
				{
					this._c_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_since", DbType="DateTime")]
		public System.Nullable<System.DateTime> c_since
		{
			get
			{
				return this._c_since;
			}
			set
			{
				if ((this._c_since != value))
				{
					this._c_since = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_middle", DbType="Char(2)")]
		public string c_middle
		{
			get
			{
				return this._c_middle;
			}
			set
			{
				if ((this._c_middle != value))
				{
					this._c_middle = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c_data", DbType="Char(500)")]
		public string c_data
		{
			get
			{
				return this._c_data;
			}
			set
			{
				if ((this._c_data != value))
				{
					this._c_data = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.warehouse")]
	public partial class warehouse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _w_id;
		
		private decimal _w_ytd;
		
		private decimal _w_tax;
		
		private string _w_name;
		
		private string _w_street_1;
		
		private string _w_street_2;
		
		private string _w_city;
		
		private string _w_state;
		
		private string _w_zip;
		
		private string _padding;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onw_idChanging(int value);
    partial void Onw_idChanged();
    partial void Onw_ytdChanging(decimal value);
    partial void Onw_ytdChanged();
    partial void Onw_taxChanging(decimal value);
    partial void Onw_taxChanged();
    partial void Onw_nameChanging(string value);
    partial void Onw_nameChanged();
    partial void Onw_street_1Changing(string value);
    partial void Onw_street_1Changed();
    partial void Onw_street_2Changing(string value);
    partial void Onw_street_2Changed();
    partial void Onw_cityChanging(string value);
    partial void Onw_cityChanged();
    partial void Onw_stateChanging(string value);
    partial void Onw_stateChanged();
    partial void Onw_zipChanging(string value);
    partial void Onw_zipChanged();
    partial void OnpaddingChanging(string value);
    partial void OnpaddingChanged();
    #endregion
		
		public warehouse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int w_id
		{
			get
			{
				return this._w_id;
			}
			set
			{
				if ((this._w_id != value))
				{
					this.Onw_idChanging(value);
					this.SendPropertyChanging();
					this._w_id = value;
					this.SendPropertyChanged("w_id");
					this.Onw_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_ytd", DbType="Money NOT NULL")]
		public decimal w_ytd
		{
			get
			{
				return this._w_ytd;
			}
			set
			{
				if ((this._w_ytd != value))
				{
					this.Onw_ytdChanging(value);
					this.SendPropertyChanging();
					this._w_ytd = value;
					this.SendPropertyChanged("w_ytd");
					this.Onw_ytdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_tax", DbType="SmallMoney NOT NULL")]
		public decimal w_tax
		{
			get
			{
				return this._w_tax;
			}
			set
			{
				if ((this._w_tax != value))
				{
					this.Onw_taxChanging(value);
					this.SendPropertyChanging();
					this._w_tax = value;
					this.SendPropertyChanged("w_tax");
					this.Onw_taxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_name", DbType="Char(10)")]
		public string w_name
		{
			get
			{
				return this._w_name;
			}
			set
			{
				if ((this._w_name != value))
				{
					this.Onw_nameChanging(value);
					this.SendPropertyChanging();
					this._w_name = value;
					this.SendPropertyChanged("w_name");
					this.Onw_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_street_1", DbType="Char(20)")]
		public string w_street_1
		{
			get
			{
				return this._w_street_1;
			}
			set
			{
				if ((this._w_street_1 != value))
				{
					this.Onw_street_1Changing(value);
					this.SendPropertyChanging();
					this._w_street_1 = value;
					this.SendPropertyChanged("w_street_1");
					this.Onw_street_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_street_2", DbType="Char(20)")]
		public string w_street_2
		{
			get
			{
				return this._w_street_2;
			}
			set
			{
				if ((this._w_street_2 != value))
				{
					this.Onw_street_2Changing(value);
					this.SendPropertyChanging();
					this._w_street_2 = value;
					this.SendPropertyChanged("w_street_2");
					this.Onw_street_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_city", DbType="Char(20)")]
		public string w_city
		{
			get
			{
				return this._w_city;
			}
			set
			{
				if ((this._w_city != value))
				{
					this.Onw_cityChanging(value);
					this.SendPropertyChanging();
					this._w_city = value;
					this.SendPropertyChanged("w_city");
					this.Onw_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_state", DbType="Char(2)")]
		public string w_state
		{
			get
			{
				return this._w_state;
			}
			set
			{
				if ((this._w_state != value))
				{
					this.Onw_stateChanging(value);
					this.SendPropertyChanging();
					this._w_state = value;
					this.SendPropertyChanged("w_state");
					this.Onw_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_w_zip", DbType="Char(9)")]
		public string w_zip
		{
			get
			{
				return this._w_zip;
			}
			set
			{
				if ((this._w_zip != value))
				{
					this.Onw_zipChanging(value);
					this.SendPropertyChanging();
					this._w_zip = value;
					this.SendPropertyChanged("w_zip");
					this.Onw_zipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_padding", DbType="Char(4000) NOT NULL", CanBeNull=false)]
		public string padding
		{
			get
			{
				return this._padding;
			}
			set
			{
				if ((this._padding != value))
				{
					this.OnpaddingChanging(value);
					this.SendPropertyChanging();
					this._padding = value;
					this.SendPropertyChanged("padding");
					this.OnpaddingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.district")]
	public partial class district : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _d_id;
		
		private int _d_w_id;
		
		private decimal _d_ytd;
		
		private System.Nullable<int> _d_next_o_id;
		
		private System.Nullable<decimal> _d_tax;
		
		private string _d_name;
		
		private string _d_street_1;
		
		private string _d_street_2;
		
		private string _d_city;
		
		private string _d_state;
		
		private string _d_zip;
		
		private string _padding;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ond_idChanging(byte value);
    partial void Ond_idChanged();
    partial void Ond_w_idChanging(int value);
    partial void Ond_w_idChanged();
    partial void Ond_ytdChanging(decimal value);
    partial void Ond_ytdChanged();
    partial void Ond_next_o_idChanging(System.Nullable<int> value);
    partial void Ond_next_o_idChanged();
    partial void Ond_taxChanging(System.Nullable<decimal> value);
    partial void Ond_taxChanged();
    partial void Ond_nameChanging(string value);
    partial void Ond_nameChanged();
    partial void Ond_street_1Changing(string value);
    partial void Ond_street_1Changed();
    partial void Ond_street_2Changing(string value);
    partial void Ond_street_2Changed();
    partial void Ond_cityChanging(string value);
    partial void Ond_cityChanged();
    partial void Ond_stateChanging(string value);
    partial void Ond_stateChanged();
    partial void Ond_zipChanging(string value);
    partial void Ond_zipChanged();
    partial void OnpaddingChanging(string value);
    partial void OnpaddingChanged();
    #endregion
		
		public district()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_id", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte d_id
		{
			get
			{
				return this._d_id;
			}
			set
			{
				if ((this._d_id != value))
				{
					this.Ond_idChanging(value);
					this.SendPropertyChanging();
					this._d_id = value;
					this.SendPropertyChanged("d_id");
					this.Ond_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_w_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int d_w_id
		{
			get
			{
				return this._d_w_id;
			}
			set
			{
				if ((this._d_w_id != value))
				{
					this.Ond_w_idChanging(value);
					this.SendPropertyChanging();
					this._d_w_id = value;
					this.SendPropertyChanged("d_w_id");
					this.Ond_w_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_ytd", DbType="Money NOT NULL")]
		public decimal d_ytd
		{
			get
			{
				return this._d_ytd;
			}
			set
			{
				if ((this._d_ytd != value))
				{
					this.Ond_ytdChanging(value);
					this.SendPropertyChanging();
					this._d_ytd = value;
					this.SendPropertyChanged("d_ytd");
					this.Ond_ytdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_next_o_id", DbType="Int")]
		public System.Nullable<int> d_next_o_id
		{
			get
			{
				return this._d_next_o_id;
			}
			set
			{
				if ((this._d_next_o_id != value))
				{
					this.Ond_next_o_idChanging(value);
					this.SendPropertyChanging();
					this._d_next_o_id = value;
					this.SendPropertyChanged("d_next_o_id");
					this.Ond_next_o_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_tax", DbType="SmallMoney")]
		public System.Nullable<decimal> d_tax
		{
			get
			{
				return this._d_tax;
			}
			set
			{
				if ((this._d_tax != value))
				{
					this.Ond_taxChanging(value);
					this.SendPropertyChanging();
					this._d_tax = value;
					this.SendPropertyChanged("d_tax");
					this.Ond_taxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_name", DbType="Char(10)")]
		public string d_name
		{
			get
			{
				return this._d_name;
			}
			set
			{
				if ((this._d_name != value))
				{
					this.Ond_nameChanging(value);
					this.SendPropertyChanging();
					this._d_name = value;
					this.SendPropertyChanged("d_name");
					this.Ond_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_street_1", DbType="Char(20)")]
		public string d_street_1
		{
			get
			{
				return this._d_street_1;
			}
			set
			{
				if ((this._d_street_1 != value))
				{
					this.Ond_street_1Changing(value);
					this.SendPropertyChanging();
					this._d_street_1 = value;
					this.SendPropertyChanged("d_street_1");
					this.Ond_street_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_street_2", DbType="Char(20)")]
		public string d_street_2
		{
			get
			{
				return this._d_street_2;
			}
			set
			{
				if ((this._d_street_2 != value))
				{
					this.Ond_street_2Changing(value);
					this.SendPropertyChanging();
					this._d_street_2 = value;
					this.SendPropertyChanged("d_street_2");
					this.Ond_street_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_city", DbType="Char(20)")]
		public string d_city
		{
			get
			{
				return this._d_city;
			}
			set
			{
				if ((this._d_city != value))
				{
					this.Ond_cityChanging(value);
					this.SendPropertyChanging();
					this._d_city = value;
					this.SendPropertyChanged("d_city");
					this.Ond_cityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_state", DbType="Char(2)")]
		public string d_state
		{
			get
			{
				return this._d_state;
			}
			set
			{
				if ((this._d_state != value))
				{
					this.Ond_stateChanging(value);
					this.SendPropertyChanging();
					this._d_state = value;
					this.SendPropertyChanged("d_state");
					this.Ond_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_d_zip", DbType="Char(9)")]
		public string d_zip
		{
			get
			{
				return this._d_zip;
			}
			set
			{
				if ((this._d_zip != value))
				{
					this.Ond_zipChanging(value);
					this.SendPropertyChanging();
					this._d_zip = value;
					this.SendPropertyChanged("d_zip");
					this.Ond_zipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_padding", DbType="Char(6000) NOT NULL", CanBeNull=false)]
		public string padding
		{
			get
			{
				return this._padding;
			}
			set
			{
				if ((this._padding != value))
				{
					this.OnpaddingChanging(value);
					this.SendPropertyChanging();
					this._padding = value;
					this.SendPropertyChanged("padding");
					this.OnpaddingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.history")]
	public partial class history
	{
		
		private System.Nullable<int> _h_c_id;
		
		private System.Nullable<byte> _h_c_d_id;
		
		private System.Nullable<int> _h_c_w_id;
		
		private System.Nullable<byte> _h_d_id;
		
		private System.Nullable<int> _h_w_id;
		
		private System.Nullable<System.DateTime> _h_date;
		
		private System.Nullable<decimal> _h_amount;
		
		private string _h_data;
		
		public history()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_c_id", DbType="Int")]
		public System.Nullable<int> h_c_id
		{
			get
			{
				return this._h_c_id;
			}
			set
			{
				if ((this._h_c_id != value))
				{
					this._h_c_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_c_d_id", DbType="TinyInt")]
		public System.Nullable<byte> h_c_d_id
		{
			get
			{
				return this._h_c_d_id;
			}
			set
			{
				if ((this._h_c_d_id != value))
				{
					this._h_c_d_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_c_w_id", DbType="Int")]
		public System.Nullable<int> h_c_w_id
		{
			get
			{
				return this._h_c_w_id;
			}
			set
			{
				if ((this._h_c_w_id != value))
				{
					this._h_c_w_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_d_id", DbType="TinyInt")]
		public System.Nullable<byte> h_d_id
		{
			get
			{
				return this._h_d_id;
			}
			set
			{
				if ((this._h_d_id != value))
				{
					this._h_d_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_w_id", DbType="Int")]
		public System.Nullable<int> h_w_id
		{
			get
			{
				return this._h_w_id;
			}
			set
			{
				if ((this._h_w_id != value))
				{
					this._h_w_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> h_date
		{
			get
			{
				return this._h_date;
			}
			set
			{
				if ((this._h_date != value))
				{
					this._h_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_amount", DbType="SmallMoney")]
		public System.Nullable<decimal> h_amount
		{
			get
			{
				return this._h_amount;
			}
			set
			{
				if ((this._h_amount != value))
				{
					this._h_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_h_data", DbType="Char(24)")]
		public string h_data
		{
			get
			{
				return this._h_data;
			}
			set
			{
				if ((this._h_data != value))
				{
					this._h_data = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.item")]
	public partial class item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i_id;
		
		private string _i_name;
		
		private System.Nullable<decimal> _i_price;
		
		private string _i_data;
		
		private System.Nullable<int> _i_im_id;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oni_idChanging(int value);
    partial void Oni_idChanged();
    partial void Oni_nameChanging(string value);
    partial void Oni_nameChanged();
    partial void Oni_priceChanging(System.Nullable<decimal> value);
    partial void Oni_priceChanged();
    partial void Oni_dataChanging(string value);
    partial void Oni_dataChanged();
    partial void Oni_im_idChanging(System.Nullable<int> value);
    partial void Oni_im_idChanged();
    #endregion
		
		public item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int i_id
		{
			get
			{
				return this._i_id;
			}
			set
			{
				if ((this._i_id != value))
				{
					this.Oni_idChanging(value);
					this.SendPropertyChanging();
					this._i_id = value;
					this.SendPropertyChanged("i_id");
					this.Oni_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_name", DbType="Char(24)")]
		public string i_name
		{
			get
			{
				return this._i_name;
			}
			set
			{
				if ((this._i_name != value))
				{
					this.Oni_nameChanging(value);
					this.SendPropertyChanging();
					this._i_name = value;
					this.SendPropertyChanged("i_name");
					this.Oni_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_price", DbType="SmallMoney")]
		public System.Nullable<decimal> i_price
		{
			get
			{
				return this._i_price;
			}
			set
			{
				if ((this._i_price != value))
				{
					this.Oni_priceChanging(value);
					this.SendPropertyChanging();
					this._i_price = value;
					this.SendPropertyChanged("i_price");
					this.Oni_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_data", DbType="Char(50)")]
		public string i_data
		{
			get
			{
				return this._i_data;
			}
			set
			{
				if ((this._i_data != value))
				{
					this.Oni_dataChanging(value);
					this.SendPropertyChanging();
					this._i_data = value;
					this.SendPropertyChanged("i_data");
					this.Oni_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i_im_id", DbType="Int")]
		public System.Nullable<int> i_im_id
		{
			get
			{
				return this._i_im_id;
			}
			set
			{
				if ((this._i_im_id != value))
				{
					this.Oni_im_idChanging(value);
					this.SendPropertyChanging();
					this._i_im_id = value;
					this.SendPropertyChanged("i_im_id");
					this.Oni_im_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.new_order")]
	public partial class new_order
	{
		
		private int _no_o_id;
		
		private byte _no_d_id;
		
		private int _no_w_id;
		
		public new_order()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_o_id", DbType="Int NOT NULL")]
		public int no_o_id
		{
			get
			{
				return this._no_o_id;
			}
			set
			{
				if ((this._no_o_id != value))
				{
					this._no_o_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_d_id", DbType="TinyInt NOT NULL")]
		public byte no_d_id
		{
			get
			{
				return this._no_d_id;
			}
			set
			{
				if ((this._no_d_id != value))
				{
					this._no_d_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_w_id", DbType="Int NOT NULL")]
		public int no_w_id
		{
			get
			{
				return this._no_w_id;
			}
			set
			{
				if ((this._no_w_id != value))
				{
					this._no_w_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_line")]
	public partial class order_line
	{
		
		private int _ol_o_id;
		
		private byte _ol_d_id;
		
		private int _ol_w_id;
		
		private byte _ol_number;
		
		private System.Nullable<int> _ol_i_id;
		
		private System.Nullable<System.DateTime> _ol_delivery_d;
		
		private System.Nullable<decimal> _ol_amount;
		
		private System.Nullable<int> _ol_supply_w_id;
		
		private System.Nullable<short> _ol_quantity;
		
		private string _ol_dist_info;
		
		public order_line()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_o_id", DbType="Int NOT NULL")]
		public int ol_o_id
		{
			get
			{
				return this._ol_o_id;
			}
			set
			{
				if ((this._ol_o_id != value))
				{
					this._ol_o_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_d_id", DbType="TinyInt NOT NULL")]
		public byte ol_d_id
		{
			get
			{
				return this._ol_d_id;
			}
			set
			{
				if ((this._ol_d_id != value))
				{
					this._ol_d_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_w_id", DbType="Int NOT NULL")]
		public int ol_w_id
		{
			get
			{
				return this._ol_w_id;
			}
			set
			{
				if ((this._ol_w_id != value))
				{
					this._ol_w_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_number", DbType="TinyInt NOT NULL")]
		public byte ol_number
		{
			get
			{
				return this._ol_number;
			}
			set
			{
				if ((this._ol_number != value))
				{
					this._ol_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_i_id", DbType="Int")]
		public System.Nullable<int> ol_i_id
		{
			get
			{
				return this._ol_i_id;
			}
			set
			{
				if ((this._ol_i_id != value))
				{
					this._ol_i_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_delivery_d", DbType="DateTime")]
		public System.Nullable<System.DateTime> ol_delivery_d
		{
			get
			{
				return this._ol_delivery_d;
			}
			set
			{
				if ((this._ol_delivery_d != value))
				{
					this._ol_delivery_d = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_amount", DbType="SmallMoney")]
		public System.Nullable<decimal> ol_amount
		{
			get
			{
				return this._ol_amount;
			}
			set
			{
				if ((this._ol_amount != value))
				{
					this._ol_amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_supply_w_id", DbType="Int")]
		public System.Nullable<int> ol_supply_w_id
		{
			get
			{
				return this._ol_supply_w_id;
			}
			set
			{
				if ((this._ol_supply_w_id != value))
				{
					this._ol_supply_w_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_quantity", DbType="SmallInt")]
		public System.Nullable<short> ol_quantity
		{
			get
			{
				return this._ol_quantity;
			}
			set
			{
				if ((this._ol_quantity != value))
				{
					this._ol_quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ol_dist_info", DbType="Char(24)")]
		public string ol_dist_info
		{
			get
			{
				return this._ol_dist_info;
			}
			set
			{
				if ((this._ol_dist_info != value))
				{
					this._ol_dist_info = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.orders")]
	public partial class orders
	{
		
		private int _o_id;
		
		private byte _o_d_id;
		
		private int _o_w_id;
		
		private int _o_c_id;
		
		private System.Nullable<byte> _o_carrier_id;
		
		private System.Nullable<byte> _o_ol_cnt;
		
		private System.Nullable<byte> _o_all_local;
		
		private System.Nullable<System.DateTime> _o_entry_d;
		
		public orders()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_id", DbType="Int NOT NULL")]
		public int o_id
		{
			get
			{
				return this._o_id;
			}
			set
			{
				if ((this._o_id != value))
				{
					this._o_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_d_id", DbType="TinyInt NOT NULL")]
		public byte o_d_id
		{
			get
			{
				return this._o_d_id;
			}
			set
			{
				if ((this._o_d_id != value))
				{
					this._o_d_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_w_id", DbType="Int NOT NULL")]
		public int o_w_id
		{
			get
			{
				return this._o_w_id;
			}
			set
			{
				if ((this._o_w_id != value))
				{
					this._o_w_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_c_id", DbType="Int NOT NULL")]
		public int o_c_id
		{
			get
			{
				return this._o_c_id;
			}
			set
			{
				if ((this._o_c_id != value))
				{
					this._o_c_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_carrier_id", DbType="TinyInt")]
		public System.Nullable<byte> o_carrier_id
		{
			get
			{
				return this._o_carrier_id;
			}
			set
			{
				if ((this._o_carrier_id != value))
				{
					this._o_carrier_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_ol_cnt", DbType="TinyInt")]
		public System.Nullable<byte> o_ol_cnt
		{
			get
			{
				return this._o_ol_cnt;
			}
			set
			{
				if ((this._o_ol_cnt != value))
				{
					this._o_ol_cnt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_all_local", DbType="TinyInt")]
		public System.Nullable<byte> o_all_local
		{
			get
			{
				return this._o_all_local;
			}
			set
			{
				if ((this._o_all_local != value))
				{
					this._o_all_local = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_o_entry_d", DbType="DateTime")]
		public System.Nullable<System.DateTime> o_entry_d
		{
			get
			{
				return this._o_entry_d;
			}
			set
			{
				if ((this._o_entry_d != value))
				{
					this._o_entry_d = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stock")]
	public partial class stock : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _s_i_id;
		
		private int _s_w_id;
		
		private short _s_quantity;
		
		private int _s_ytd;
		
		private System.Nullable<short> _s_order_cnt;
		
		private System.Nullable<short> _s_remote_cnt;
		
		private string _s_data;
		
		private string _s_dist_01;
		
		private string _s_dist_02;
		
		private string _s_dist_03;
		
		private string _s_dist_04;
		
		private string _s_dist_05;
		
		private string _s_dist_06;
		
		private string _s_dist_07;
		
		private string _s_dist_08;
		
		private string _s_dist_09;
		
		private string _s_dist_10;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ons_i_idChanging(int value);
    partial void Ons_i_idChanged();
    partial void Ons_w_idChanging(int value);
    partial void Ons_w_idChanged();
    partial void Ons_quantityChanging(short value);
    partial void Ons_quantityChanged();
    partial void Ons_ytdChanging(int value);
    partial void Ons_ytdChanged();
    partial void Ons_order_cntChanging(System.Nullable<short> value);
    partial void Ons_order_cntChanged();
    partial void Ons_remote_cntChanging(System.Nullable<short> value);
    partial void Ons_remote_cntChanged();
    partial void Ons_dataChanging(string value);
    partial void Ons_dataChanged();
    partial void Ons_dist_01Changing(string value);
    partial void Ons_dist_01Changed();
    partial void Ons_dist_02Changing(string value);
    partial void Ons_dist_02Changed();
    partial void Ons_dist_03Changing(string value);
    partial void Ons_dist_03Changed();
    partial void Ons_dist_04Changing(string value);
    partial void Ons_dist_04Changed();
    partial void Ons_dist_05Changing(string value);
    partial void Ons_dist_05Changed();
    partial void Ons_dist_06Changing(string value);
    partial void Ons_dist_06Changed();
    partial void Ons_dist_07Changing(string value);
    partial void Ons_dist_07Changed();
    partial void Ons_dist_08Changing(string value);
    partial void Ons_dist_08Changed();
    partial void Ons_dist_09Changing(string value);
    partial void Ons_dist_09Changed();
    partial void Ons_dist_10Changing(string value);
    partial void Ons_dist_10Changed();
    #endregion
		
		public stock()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_i_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int s_i_id
		{
			get
			{
				return this._s_i_id;
			}
			set
			{
				if ((this._s_i_id != value))
				{
					this.Ons_i_idChanging(value);
					this.SendPropertyChanging();
					this._s_i_id = value;
					this.SendPropertyChanged("s_i_id");
					this.Ons_i_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_w_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int s_w_id
		{
			get
			{
				return this._s_w_id;
			}
			set
			{
				if ((this._s_w_id != value))
				{
					this.Ons_w_idChanging(value);
					this.SendPropertyChanging();
					this._s_w_id = value;
					this.SendPropertyChanged("s_w_id");
					this.Ons_w_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_quantity", DbType="SmallInt NOT NULL")]
		public short s_quantity
		{
			get
			{
				return this._s_quantity;
			}
			set
			{
				if ((this._s_quantity != value))
				{
					this.Ons_quantityChanging(value);
					this.SendPropertyChanging();
					this._s_quantity = value;
					this.SendPropertyChanged("s_quantity");
					this.Ons_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_ytd", DbType="Int NOT NULL")]
		public int s_ytd
		{
			get
			{
				return this._s_ytd;
			}
			set
			{
				if ((this._s_ytd != value))
				{
					this.Ons_ytdChanging(value);
					this.SendPropertyChanging();
					this._s_ytd = value;
					this.SendPropertyChanged("s_ytd");
					this.Ons_ytdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_order_cnt", DbType="SmallInt")]
		public System.Nullable<short> s_order_cnt
		{
			get
			{
				return this._s_order_cnt;
			}
			set
			{
				if ((this._s_order_cnt != value))
				{
					this.Ons_order_cntChanging(value);
					this.SendPropertyChanging();
					this._s_order_cnt = value;
					this.SendPropertyChanged("s_order_cnt");
					this.Ons_order_cntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_remote_cnt", DbType="SmallInt")]
		public System.Nullable<short> s_remote_cnt
		{
			get
			{
				return this._s_remote_cnt;
			}
			set
			{
				if ((this._s_remote_cnt != value))
				{
					this.Ons_remote_cntChanging(value);
					this.SendPropertyChanging();
					this._s_remote_cnt = value;
					this.SendPropertyChanged("s_remote_cnt");
					this.Ons_remote_cntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_data", DbType="Char(50)")]
		public string s_data
		{
			get
			{
				return this._s_data;
			}
			set
			{
				if ((this._s_data != value))
				{
					this.Ons_dataChanging(value);
					this.SendPropertyChanging();
					this._s_data = value;
					this.SendPropertyChanged("s_data");
					this.Ons_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_01", DbType="Char(24)")]
		public string s_dist_01
		{
			get
			{
				return this._s_dist_01;
			}
			set
			{
				if ((this._s_dist_01 != value))
				{
					this.Ons_dist_01Changing(value);
					this.SendPropertyChanging();
					this._s_dist_01 = value;
					this.SendPropertyChanged("s_dist_01");
					this.Ons_dist_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_02", DbType="Char(24)")]
		public string s_dist_02
		{
			get
			{
				return this._s_dist_02;
			}
			set
			{
				if ((this._s_dist_02 != value))
				{
					this.Ons_dist_02Changing(value);
					this.SendPropertyChanging();
					this._s_dist_02 = value;
					this.SendPropertyChanged("s_dist_02");
					this.Ons_dist_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_03", DbType="Char(24)")]
		public string s_dist_03
		{
			get
			{
				return this._s_dist_03;
			}
			set
			{
				if ((this._s_dist_03 != value))
				{
					this.Ons_dist_03Changing(value);
					this.SendPropertyChanging();
					this._s_dist_03 = value;
					this.SendPropertyChanged("s_dist_03");
					this.Ons_dist_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_04", DbType="Char(24)")]
		public string s_dist_04
		{
			get
			{
				return this._s_dist_04;
			}
			set
			{
				if ((this._s_dist_04 != value))
				{
					this.Ons_dist_04Changing(value);
					this.SendPropertyChanging();
					this._s_dist_04 = value;
					this.SendPropertyChanged("s_dist_04");
					this.Ons_dist_04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_05", DbType="Char(24)")]
		public string s_dist_05
		{
			get
			{
				return this._s_dist_05;
			}
			set
			{
				if ((this._s_dist_05 != value))
				{
					this.Ons_dist_05Changing(value);
					this.SendPropertyChanging();
					this._s_dist_05 = value;
					this.SendPropertyChanged("s_dist_05");
					this.Ons_dist_05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_06", DbType="Char(24)")]
		public string s_dist_06
		{
			get
			{
				return this._s_dist_06;
			}
			set
			{
				if ((this._s_dist_06 != value))
				{
					this.Ons_dist_06Changing(value);
					this.SendPropertyChanging();
					this._s_dist_06 = value;
					this.SendPropertyChanged("s_dist_06");
					this.Ons_dist_06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_07", DbType="Char(24)")]
		public string s_dist_07
		{
			get
			{
				return this._s_dist_07;
			}
			set
			{
				if ((this._s_dist_07 != value))
				{
					this.Ons_dist_07Changing(value);
					this.SendPropertyChanging();
					this._s_dist_07 = value;
					this.SendPropertyChanged("s_dist_07");
					this.Ons_dist_07Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_08", DbType="Char(24)")]
		public string s_dist_08
		{
			get
			{
				return this._s_dist_08;
			}
			set
			{
				if ((this._s_dist_08 != value))
				{
					this.Ons_dist_08Changing(value);
					this.SendPropertyChanging();
					this._s_dist_08 = value;
					this.SendPropertyChanged("s_dist_08");
					this.Ons_dist_08Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_09", DbType="Char(24)")]
		public string s_dist_09
		{
			get
			{
				return this._s_dist_09;
			}
			set
			{
				if ((this._s_dist_09 != value))
				{
					this.Ons_dist_09Changing(value);
					this.SendPropertyChanging();
					this._s_dist_09 = value;
					this.SendPropertyChanged("s_dist_09");
					this.Ons_dist_09Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_s_dist_10", DbType="Char(24)")]
		public string s_dist_10
		{
			get
			{
				return this._s_dist_10;
			}
			set
			{
				if ((this._s_dist_10 != value))
				{
					this.Ons_dist_10Changing(value);
					this.SendPropertyChanging();
					this._s_dist_10 = value;
					this.SendPropertyChanged("s_dist_10");
					this.Ons_dist_10Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
